In [9]:
pd.options.display.max_rows = 9999
pd.options.display.max_columns = 9999

import matplotlib.pyplot as plt
from matplotlib import rc
import seaborn as sns
%matplotlib inline
rc('font', family='AppleGothic')

plt.rcParams['axes.unicode_minus'] = False

In [10]:
raw_df = pd.read_csv("resources/2016_1분기보고서_03_포괄손익계산서_20190418.txt",sep = "\t",  engine='python', encoding = "cp949")

# 포괄손익계산서 Statement of comprehensive income , 包括損益計算書

정기간 동안 기업이 달성한 경영성과를 보여주기 위해 한국채택국제회계기준에서 요구하는 재무제표로, 총포괄손익(주주와의 자본거래를 제외한 모든 거래로 인해 발생한 자본의 변동)에 <br> 해당하는 당기순손익과 기타포괄손익 정보(총포괄손익에 포함되지만 당기손익이 아닌 수익과 비용)를 제공한다.

In [11]:
raw_df.head(5)

,재무제표종류,종목코드,회사명,시장구분,업종,업종명,결산월,결산기준일,보고서종류,통화,항목코드,항목명,당기 1분기 3개월,당기 1분기 누적,전기 1분기 3개월,전기 1분기 누적,전기,전전기
0,"포괄손익계산서, 기능별 분류(세후기타포괄손익) - 별도재무제표",[060310],3S,코스닥시장상장법인,262,전자부품 제조업,3,2016-06-30,1분기보고서,KRW,ifrs_Revenue,수익(매출액),"5,975,861,071","5,975,861,071","5,116,455,520","5,116,455,520","19,425,637,572","21,104,219,053"
1,"포괄손익계산서, 기능별 분류(세후기타포괄손익) - 별도재무제표",[060310],3S,코스닥시장상장법인,262,전자부품 제조업,3,2016-06-30,1분기보고서,KRW,ifrs_CostOfSales,매출원가,"4,997,565,721","4,997,565,721","4,353,993,084","4,353,993,084","16,195,826,820","19,807,461,698"
2,"포괄손익계산서, 기능별 분류(세후기타포괄손익) - 별도재무제표",[060310],3S,코스닥시장상장법인,262,전자부품 제조업,3,2016-06-30,1분기보고서,KRW,ifrs_GrossProfit,매출총이익,"978,295,350","978,295,350","762,462,436","762,462,436","3,229,810,752","1,296,757,355"
3,"포괄손익계산서, 기능별 분류(세후기타포괄손익) - 별도재무제표",[060310],3S,코스닥시장상장법인,262,전자부품 제조업,3,2016-06-30,1분기보고서,KRW,dart_TotalSellingGeneralAdministrativeExpenses,판매비와관리비,"948,485,967","948,485,967","650,779,885","650,779,885","2,324,704,067","5,402,979,409"
4,"포괄손익계산서, 기능별 분류(세후기타포괄손익) - 별도재무제표",[060310],3S,코스닥시장상장법인,262,전자부품 제조업,3,2016-06-30,1분기보고서,KRW,dart_OperatingIncomeLoss,영업이익(손실),"29,809,383","29,809,383","111,682,551","111,682,551","905,106,685","-4,106,222,054"

In [12]:
raw_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39919 entries, 0 to 39918
Data columns (total 18 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   재무제표종류      39919 non-null  object
 1   종목코드        39919 non-null  object
 2   회사명         39919 non-null  object
 3   시장구분        39919 non-null  object
 4   업종          39919 non-null  int64
 5   업종명         39919 non-null  object
 6   결산월         39919 non-null  int64
 7   결산기준일       39919 non-null  object
 8   보고서종류       39919 non-null  object
 9   통화          39919 non-null  object
 10  항목코드        39919 non-null  object
 11  항목명         39917 non-null  object
 12  당기 1분기 3개월  34665 non-null  object
 13  당기 1분기 누적   34638 non-null  object
 14  전기 1분기 3개월  34452 non-null  object
 15  전기 1분기 누적   34426 non-null  object
 16  전기          36565 non-null  object
 17  전전기         36320 non-null  object
dtypes: int64(2), object(16)
memory usage: 5.5+ MB

In [14]:
raw_cn = pd.read_csv('cn_16_17.csv')
raw_cn.tail()

          기업명    직전    현재     등급결정일
180    한국서부발전   AAA   AAA  20170518
181    오리온홀딩스    AA    AA  20170516
182      호텔신라    AA    AA  20170516
183   금호피앤비화학  BBB+  BBB+  20170516
184  코오롱인더스트리     A     A  20170516

## <font color = "#DAF7A6"> * missing values

In [15]:
raw_df.isnull().sum()

재무제표종류           0
종목코드             0
회사명              0
시장구분             0
업종               0
업종명              0
결산월              0
결산기준일            0
보고서종류            0
통화               0
항목코드             0
항목명              2
당기 1분기 3개월    5254
당기 1분기 누적     5281
전기 1분기 3개월    5467
전기 1분기 누적     5493
전기            3354
전전기           3599
dtype: int64

### <font color = "#DAF7A5"> drop columns

In [16]:
df = raw_df[['종목코드', '회사명','항목명', '당기 1분기 누적']]
df.head()

       종목코드 회사명       항목명      당기 1분기 누적
0  [060310]  3S   수익(매출액)  5,975,861,071
1  [060310]  3S      매출원가  4,997,565,721
2  [060310]  3S     매출총이익    978,295,350
3  [060310]  3S   판매비와관리비    948,485,967
4  [060310]  3S  영업이익(손실)     29,809,383

In [17]:
cn = raw_cn[['기업명', '직전','현재']]
cn.head()

      기업명   직전   현재
0  메리츠캐피탈    A    A
1  페이퍼코리아  BB-  B-↓
2    디엠에스   BB   BB
3   웅진에너지  CCC  CCC
4    대웅제약  AA-   A+

### <font color = "#DAF7A5"> 매칭되는 기업명으로 정리 
### df1 ⇩

In [25]:
df_match_cn = df[df.회사명.isin(cn.기업명)]
# df[df.a.isin(df1.a)]
df_match_cn.head() # len = 1603행
df1 = df_match_cn

In [26]:
df1["항목명"] = df1["항목명"].apply(lambda x :  str(x).replace(" ",""))
df_list = ["매출액","당기순이익","금융비용","금융원가","감가상각비","무형자산상각비","매출원가","판매관리비"]
df1[df1["항목명"].str.contains("매출액","당기순이익")]

           종목코드         회사명                     항목명           당기 1분기 누적
1411   [000040]       KR모터스                     매출액      18,791,545,861
1572   [093050]          LF                     매출액     343,339,287,965
3181   [000500]        가온전선                     매출액     175,837,327,546
5621   [002350]       넥센타이어                 수익(매출액)     360,710,234,502
6230   [023590]        다우기술                     매출액      65,050,338,286
6717   [001680]          대상                     매출액     446,120,933,751
7096   [069620]        대웅제약                 수익(매출액)     190,451,873,606
9314   [006040]        동원산업                     매출액     167,090,238,812
9315   [006040]        동원산업                  어획물매출액      51,679,215,463
9316   [006040]        동원산업                   제품매출액      31,149,484,837
9317   [006040]        동원산업                   상품매출액      13,862,115,869
9318   [006040]        동원산업                   물류매출액      57,076,985,830
9319   [006040]        동원산업                   기타매출액      13,322,436,813
10846  [004000]      롯데정밀화학                     매출액     285,752,117,565
10961  [071840]      롯데하이마트                     매출액     887,700,695,530
11304  [027740]         마니커                     매출액      55,048,211,764
14339  [028260]        삼성물산                     매출액   4,559,672,268,780
14571  [000070]       삼양홀딩스                     매출액      50,721,000,000
15100  [004690]         삼천리                     매출액     986,529,416,973
15101  [004690]         삼천리                   상품매출액     976,256,986,612
15102  [004690]         삼천리                   제품매출액       7,119,389,036
15103  [004690]         삼천리                   기타매출액       3,153,041,325
15312  [000390]     삼화페인트공업                     매출액      93,251,168,407
15971  [008490]          서흥                     매출액      59,153,928,175
16675  [001430]       세아베스틸                 수익(매출액)     399,309,100,191
16723  [019440]       세아특수강                     매출액     142,655,145,998
17974  [034300]       신세계건설                     매출액     315,057,732,999
19505  [020560]      아시아나항공                     매출액   1,285,384,943,224
19969  [114810]        아이원스                     매출액      15,104,083,797
22109  [036570]       엔씨소프트                 수익(매출액)     169,355,405,079
22564  [123040]      엠에스오토텍                     매출액      52,750,194,468
23264  [007310]         오뚜기                 수익(매출액)     499,472,351,904
24566  [103130]       웅진에너지                     매출액      42,879,637,980
26381  [005950]        이수화학                 수익(매출액)     203,915,274,486
28542  [036420]      제이콘텐트리                 수익(매출액)       9,343,418,976
30316  [002380]        케이씨씨                 수익(매출액)     710,299,889,467
31573  [045970]     코아시아홀딩스                 수익(매출액)         634,947,614
33239  [052290]        트레이스                     매출액       6,639,991,713
33693  [043200]          파루                     매출액      39,880,711,065
34267  [001020]      페이퍼코리아                 수익(매출액)      90,841,966,860
34461  [005490]         포스코                     매출액   5,767,131,973,119
35884  [000140]    하이트진로홀딩스                 수익(매출액)      40,256,243,606
35945  [036460]      한국가스공사                 수익(매출액)   7,612,305,435,903
35946  [036460]      한국가스공사         재화의판매로인한수익(매출액)   7,599,875,144,555
35947  [036460]      한국가스공사            정부보조금수익(매출액)         603,134,794
35948  [036460]      한국가스공사               기타수익(매출액)      11,827,156,554
35950  [036460]      한국가스공사  재화의판매로인한수익(매출액)에대한매출원가   6,624,518,068,288
35951  [036460]      한국가스공사        기타수익(매출액)에대한매출원가       3,885,673,259
36307  [015760]      한국전력공사                     매출액  15,566,139,000,000
36308  [015760]      한국전력공사             재화의판매로인한매출액  14,485,653,000,000
36309  [015760]      한국전력공사            용역의제공으로인한매출액      42,490,000,000
36310  [015760]      한국전력공사             건설계약으로인한매출액     940,078,000,000
36981  [060980]       한라홀딩스                     매출액     147,639,795,513
37106  [128940]        한미약품                     매출액     195,447,087,764
37427  [213500]        한솔제지                     매출액     354,282,422,102
37447  [014680]       한솔케미칼                     매출액      77,463,060,066
37448  [014680]       한솔케미칼                   상품매출액       3,561,293,190
37449  [014680]       한솔케미칼                   제품매출액      73,879,023,517
37450  [014680]       한솔케미칼                   기타매출액          22,743,359
37942  [002320]          한진                 매출액(수익)     393,095,547,370
38273  [027390]  한화갤러리아타임월드                 수익(매출액)      57,495,008,763
38428  [101530]      해태제과식품                     매출액     180,525,026,531
38460  [000720]        현대건설                     매출액   2,443,824,000,000
38619  [004560]     현대비앤지스틸                     매출액     155,287,386,912
38845  [011210]        현대위아                     매출액   1,773,333,236,962
38900  [004020]        현대제철                     매출액   3,203,967,760,871
39688  [079980]         휴비스                 수익(매출액)     215,511,155,880
39802  [069260]         휴켐스                 수익(매출액)     135,619,442,531

In [98]:
df1[df1<5]

회사명
나스미디어    4
농우바이오    4
디에이피     4
세명전기     4
티엘아이     4
dtype: int64

In [70]:
### <font color = "#DAF7A5"> Values ?

### <font color = "#DAF7A5"> imputation ?

In [33]:
df['항목명'].unique()

array(['수익(매출액)', '매출원가', '매출총이익', ..., '순금융수익(비용)', '외환수익', '외환비용'],
      dtype=object)

In [91]:
df.loc[df['회사명'] == '엠제이비']

           종목코드   회사명                 항목명              당기              전기
22874  [074150]  엠제이비                 매출액   4,444,328,376   5,744,391,048
22875  [074150]  엠제이비                제품매출     110,214,780     506,801,130
22876  [074150]  엠제이비                상품매출     330,000,000       2,500,000
22877  [074150]  엠제이비                공사매출             NaN   3,558,974,000
22878  [074150]  엠제이비                용역매출   2,875,900,000     595,466,647
...         ...   ...                 ...             ...             ...
22971  [074150]  엠제이비        매도가능금융자산평가손익     -51,811,584      57,798,834
22972  [074150]  엠제이비           총포괄이익(손실)  -5,565,062,668  14,792,368,547
22973  [074150]  엠제이비                주당손익             NaN             NaN
22974  [074150]  엠제이비         기본주당순이익(손실)            -202             660
22975  [074150]  엠제이비         희석주당순이익(손실)            -154             660

[102 rows x 5 columns]

In [99]:
df.loc[df['회사명'] == '나스미디어']

          종목코드    회사명               항목명             당기             전기
5025  [089600]  나스미디어         당기순이익(손실)  9,916,023,522  7,956,450,620
5026  [089600]  나스미디어    법인세비용차감후기타포괄손익   -562,911,063   -181,541,271
5027  [089600]  나스미디어     확정급여제도의 재측정손익   -562,911,063   -181,541,271
5028  [089600]  나스미디어             총포괄손익  9,353,112,459  7,774,909,349

In [41]:
df.회사명.unique()

array(['3S', 'AJ네트웍스', 'AJ렌터카', ..., '흥국에프엔비', '흥아해운', '희림'], dtype=object)

In [47]:
df.loc[df['회사명'] == 'AJ네트웍스']

,재무제표종류,종목코드,회사명,시장구분,업종,업종명,결산월,결산기준일,보고서종류,통화,항목코드,항목명,당기,전기,전전기
17,"포괄손익계산서, 기능별 분류(세후기타포괄손익) - 별도재무제표",[095570],AJ네트웍스,유가증권시장상장법인,693,산업용 기계 및 장비 임대업,12,12/31/2015,사업보고서,KRW,ifrs_Revenue,영업수익,"196,520,251,563","194,184,554,953","20,707,731,342"
18,"포괄손익계산서, 기능별 분류(세후기타포괄손익) - 별도재무제표",[095570],AJ네트웍스,유가증권시장상장법인,693,산업용 기계 및 장비 임대업,12,12/31/2015,사업보고서,KRW,ifrs_CostOfSales,영업비용,"172,850,127,896","167,898,839,204","3,869,129,747"
19,"포괄손익계산서, 기능별 분류(세후기타포괄손익) - 별도재무제표",[095570],AJ네트웍스,유가증권시장상장법인,693,산업용 기계 및 장비 임대업,12,12/31/2015,사업보고서,KRW,entity00365387_udf_IS_201632916234426_Statemen...,영업이익,"23,670,123,667","26,285,715,749","16,838,601,595"
20,"포괄손익계산서, 기능별 분류(세후기타포괄손익) - 별도재무제표",[095570],AJ네트웍스,유가증권시장상장법인,693,산업용 기계 및 장비 임대업,12,12/31/2015,사업보고서,KRW,dart_OtherGains,기타수익,"932,498,291","422,639,674","28,550,726"
21,"포괄손익계산서, 기능별 분류(세후기타포괄손익) - 별도재무제표",[095570],AJ네트웍스,유가증권시장상장법인,693,산업용 기계 및 장비 임대업,12,12/31/2015,사업보고서,KRW,dart_OtherLosses,기타비용,"1,275,249,854","2,383,228,451","6,197,028,713"
22,"포괄손익계산서, 기능별 분류(세후기타포괄손익) - 별도재무제표",[095570],AJ네트웍스,유가증권시장상장법인,693,산업용 기계 및 장비 임대업,12,12/31/2015,사업보고서,KRW,ifrs_OtherIncomeExpenseFromSubsidiariesJointly...,종속기업투자손익,"10,649,806,631","10,483,493,695",NaN
23,"포괄손익계산서, 기능별 분류(세후기타포괄손익) - 별도재무제표",[095570],AJ네트웍스,유가증권시장상장법인,693,산업용 기계 및 장비 임대업,12,12/31/2015,사업보고서,KRW,ifrs_FinanceIncome,금융수익,"757,796,302","1,747,232,809","583,928,814"
24,"포괄손익계산서, 기능별 분류(세후기타포괄손익) - 별도재무제표",[095570],AJ네트웍스,유가증권시장상장법인,693,산업용 기계 및 장비 임대업,12,12/31/2015,사업보고서,KRW,ifrs_FinanceCosts,금융비용,"12,607,433,619","15,407,947,467","4,023,874,050"
25,"포괄손익계산서, 기능별 분류(세후기타포괄손익) - 별도재무제표",[095570],AJ네트웍스,유가증권시장상장법인,693,산업용 기계 및 장비 임대업,12,12/31/2015,사업보고서,KRW,ifrs_ProfitLossBeforeTax,법인세비용차감전순이익,"22,127,541,418","21,147,906,009","7,230,178,372"
26,"포괄손익계산서, 기능별 분류(세후기타포괄손익) - 별도재무제표",[095570],AJ네트웍스,유가증권시장상장법인,693,산업용 기계 및 장비 임대업,12,12/31/2015,사업보고서,KRW,ifrs_IncomeTaxExpenseContinuingOperations,법인세비용,"3,042,950,494","2,686,422,075","943,732,437"
27,"포괄손익계산서, 기능별 분류(세후기타포괄손익) - 별도재무제표",[095570],AJ네트웍스,유가증권시장상장법인,693,산업용 기계 및 장비 임대업,12,12/31/2015,사업보고서,KRW,ifrs_ProfitLoss,당기순이익(손실),"19,084,590,924","18,461,483,934","6,286,445,935"
28,"포괄손익계산서, 기능별 분류(세후기타포괄손익) - 별도재무제표",[095570],AJ네트웍스,유가증권시장상장법인,693,산업용 기계 및 장비 임대업,12,12/31/2015,사업보고서,KRW,ifrs_OtherComprehensiveIncome,기타포괄손익,"98,240,680","-98,391,420","-118,151,273"
29,"포괄손익계산서, 기능별 분류(세후기타포괄손익) - 별도재무제표",[095570],AJ네트웍스,유가증권시장상장법인,693,산업용 기계 및 장비 임대업,12,12/31/2015,사업보고서,KRW,entity00365387_udf_IS_2015330133713201_OtherCo...,후속적으로 당기손익으로 재분류 될 수 있는 항목,NaN,NaN,NaN
30,"포괄손익계산서, 기능별 분류(세후기타포괄손익) - 별도재무제표",[095570],AJ네트웍스,유가증권시장상장법인,693,산업용 기계 및 장비 임대업,12,12/31/2015,사업보고서,KRW,entity00365387_udf_IS_2015330133719939_OtherCo...,지분법 자본변동,"-9,054,954","-117,750,518","-144,768,773"
31,"포괄손익계산서, 기능별 분류(세후기타포괄손익) - 별도재무제표",[095570],AJ네트웍스,유가증권시장상장법인,693,산업용 기계 및 장비 임대업,12,12/31/2015,사업보고서,KRW,entity00365387_udf_IS_2015330133724286_OtherCo...,매도가능금융자산평가손익,"73,342,866","20,344,802","26,617,500"
32,"포괄손익계산서, 기능별 분류(세후기타포괄손익) - 별도재무제표",[095570],AJ네트웍스,유가증권시장상장법인,693,산업용 기계 및 장비 임대업,12,12/31/2015,사업보고서,KRW,entity00365387_udf_IS_201533013373529_OtherCom...,파생상품평가(이익)손실,"33,952,768","-985,704",NaN
33,"포괄손익계산서, 기능별 분류(세후기타포괄손익) - 별도재무제표",[095570],AJ네트웍스,유가증권시장상장법인,693,산업용 기계 및 장비 임대업,12,12/31/2015,사업보고서,KRW,ifrs_ComprehensiveIncome,당기포괄이익,"19,182,831,604","18,363,092,514","6,168,294,662"
34,"포괄손익계산서, 기능별 분류(세후기타포괄손익) - 별도재무제표",[095570],AJ네트웍스,유가증권시장상장법인,693,산업용 기계 및 장비 임대업,12,12/31/2015,사업보고서,KRW,ifrs_EarningsPerShareAbstract,주당이익 [abstract],NaN,NaN,NaN
35,"포괄손익계산서, 기능별 분류(세후기타포괄손익) - 별도재무제표",[095570],AJ네트웍스,유가증권시장상장법인,693,산업용 기계 및 장비 임대업,12,12/31/2015,사업보고서,KRW,ifrs_BasicEarningsLossPerShare,기본주당이익,"2,424","3,046","2,522"
36,"포괄손익계산서, 기능별 분류(세후기타포괄손익) - 별도재무제표",[095570],AJ네트웍스,유가증권시장상장법인,693,산업용 기계 및 장비 임대업,12,12/31/2015,사업보고서,KRW,ifrs_DilutedEarningsLossPerShare,희석주당이익,"2,424","3,046","2,522"