In [20]:
pd.options.display.max_rows = 9999
pd.options.display.max_columns = 9999

import matplotlib.pyplot as plt
from matplotlib import rc
import seaborn as sns
%matplotlib inline
rc('font', family='AppleGothic')

plt.rcParams['axes.unicode_minus'] = False

In [25]:
raw_df = pd.read_excel("resources/일일등급속보_20200609.xls")

raw_df.head()

,기업신용평가 347건,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,기업명,평정,직전,직전,현재,현재,등급결정일,등급확정일,유효기간
1,NaN,NaN,등급,전망,등급,전망,NaN,NaN,NaN
2,삼화페인트공업(주),수시,A-,Negative,BBB+,Stable,2019.12.27,2019.12.30,2021.03.31
3,동국산업(주),본,NaN,NaN,BBB+,Stable,2019.12.27,2019.12.27,2020.12.27
4,한국해외인프라도시개발지원공사,본,NaN,NaN,AAA,Stable,2019.12.23,2019.12.23,2020.12.23

In [27]:
def screen_name(df):
    df = df[[df.columns[0],'Unnamed: 2','Unnamed: 4','Unnamed: 6']]
    df.columns = df.loc[0]
    df = df.drop([0,1])
    df["등급결정일"] = df["등급결정일"].apply(lambda x: int(str(x).replace(".","")))
    
    return df

In [29]:
df = screen_name(raw_df)
df.head()

0              기업명   직전    현재     등급결정일
2       삼화페인트공업(주)   A-  BBB+  20191227
3          동국산업(주)  NaN  BBB+  20191227
4  한국해외인프라도시개발지원공사  NaN   AAA  20191223
5          한미약품(주)   A+    A+  20191218
6       중국농업은행서울지점  NaN   AAA  20191205